column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
# Possible options: Always, NoSingleString, NoSingleTable, None.
call_parentheses = "None"
# no_call_parentheses = true
