# Language support configuration.
# <https://docs.helix-editor.com/master/languages.html>
# <https://github.com/helix-editor/helix/blob/master/languages.toml>

[use-grammars]
only = [
 'bash',
 'c',
 'c-sharp',
 'cmake',
 # 'comment',
 'cpp',
 'css',
 'dart',
 'dockerfile',
 'elixir',
 # 'elm',
 # 'erlang',
 'fish',
 'git-commit',
 'git-config',
 'git-diff',
 'git-rebase',
 # 'glsl',
 'go',
 'graphql',
 'haskell',
 # 'hcl',
 'html',
 # 'iex',
 'java',
 'javascript',
 'json',
 'julia',
 'kotlin',
 'latex',
 # 'lean',
 # 'ledger',
 # 'llvm',
 # 'llvm-mir',
 'lua',
 'make',
 'markdown',
 # 'nix',
 # 'ocaml',
 # 'ocaml-interface',
 'org',
 # 'perl',
 # 'php',
 'protobuf',
 'python',
 'regex',
 # 'rescript',
 'ruby',
 'rust',
 'scala',
 # 'solidity',
 # 'svelte',
 # 'tablegen',
 'toml',
 # 'tsq',
 # 'tsx',
 # 'twig',
 'typescript',
 # 'vue',
 # 'wgsl',
 'yaml',
 'zig',
]
