[helpers]

[default]

[default.files]
gitconfig = "~/.gitconfig"
"conda.yml" = "~/.condarc"
npmrc = "~/.npmrc"

# windows diff
pip = "~/.config/pip/pip.conf"
"lsd.yml" = "~/.config/lsd/config.yaml"
"bottom.toml" = "~/.config/bottom/bottom.toml"
"bat.cfg" = "~/.config/bat/config"
alacritty = { target = "~/.config/alacritty/", type = "symbolic" }
so = { target = "~/.config/so", type = "symbolic" }
"s.cfg" = "~/.config/s/config"

[default.variables]
username = "Xavier Younger"
# locale   = "zh-cn"


[vim]

depends = [ "default" ]

[vim.files]
vimrc = { target = "~/.vimrc", type = "symbolic" }
gvimrc = { target = "~/.gvimrc", type = "symbolic" }


[win]
depends = [ "default" ]

[win.files]
wslconfig = "~/.wslconfig"

