# [helpers]
# hex2rgb = ".dotter/helpers/hex2rgb.rhai"

[default]

[default.variables]

username = "Xavier Younger"
locale = "zh-cn"
os = "linux"
font = "Hack"
font_size = 12
nerd_font = "Nerd Font"
colorscheme = "dracula"
primary_color = "#CCCCCC"
background_color = "#333333"
screen_size = "1920x1080"
terminal = "xfce4-terminal"

[default.files]

"conda.yml" = "~/.condarc"
npmrc = "~/.npmrc"
yarnrc = "~/.yarnrc"
gemrc = "~/.gemrc"
"maven.xml" = "~/.m2/settings.xml"
rgrc = "~/.config/rgrc"
netrc = "~/.netrc"
emacs = "~/.config/emacs"
spacemacs = "~/.spacemacs"
Doom = { target = "~/.doom.d", type = "symbolic" }
SpaceVim = { target = "~/.SpaceVim.d", type = "symbolic" }
"cargo.toml" = "~/.cargo/config.toml"
"starship.toml" = "~/.config/starship.toml"
"fuck.py" = "~/.config/thefuck/settings.py"
"leetcode.json" = "~/.lc/plugins.json"
AppSettings = { target = "~/AppSettings", type = "symbolic" }
"s.cfg" = "~/.config/s/config"
"gpg.conf" = "~/.gnupg/gpg.conf"
"markdownlint.jsonc" = "~/.markdownlintrc"
"gh-prs.yml" = "~/.config/prs/config.yml"
git = { target = "~/.config/git", type = "symbolic" }
Wezterm = { target = "~/.config/wezterm", type = "symbolic" }
ideavimrc = "~/.ideavimrc"

# windows diff
vim = { target = "~/.vim", type = "symbolic" }
pip = "~/.config/pip/pip.conf"
"lsd.yml" = "~/.config/lsd/config.yaml"
"bottom.toml" = "~/.config/bottom/bottom.toml"
"bat.cfg" = "~/.config/bat/config"
Alacritty = { target = "~/.config/alacritty/", type = "symbolic" }
"Alacritty/alacritty.yml" = { target = "~/.config/alacritty/alacritty.yml", type = "template" }
So = { target = "~/.config/so", type = "symbolic" }
"gh.yml" = "~/.config/gh/config.yml"
vivid = { target = "~/.config/vivid", type = "symbolic" }
fd = { target = "~/.config/fd", type = "symbolic" }
broot = { target = "~/.config/broot", type = "symbolic" }
helix = { target = "~/.config/helix", type = "symbolic" }
espanso = { target = "~/.config/espanso", type = "symbolic" }
"poetry.toml" = "~/.config/pypoetry/config.toml"
"youtube-dl/conf" = "~/.config/youtube-dl/config"
"yt-dlp/config" = "~/.config/yt-dlp/config"

# mac diff
goenv = "~/.config/go/env"
"clangd.yaml" = "~/.config/clangd/config.yaml"

[vim]

[vim.files]

vimrc = { target = "~/.vimrc", type = "symbolic" }
gvimrc = { target = "~/.gvimrc", type = "symbolic" }

[shell]

depends = ["default"]

[shell.files]

profile = "~/.profile"
bin = { target = "~/bin", type = "symbolic" }

[bash]

[bash.files]

bash_profile = "~/.bash_profile"
bashrc = "~/.bashrc"
inputrc = "~/.inputrc"

[zsh]

[zsh.files]

zsh = "~/zsh"
"zsh/zshenv" = "~/.zshenv"
"zsh/zprofile" = "~/zsh/.zprofile"
"zsh/zshrc" = "~/zsh/.zshrc"
"zsh/p10k" = "~/.p10k.zsh"

[fish]

[fish.files]

fish = "~/.config/fish"

[linux]

depends = ["shell", "bash", "zsh", "fish"]

[linux.files]

"tmux.conf.local.sh" = "~/.tmux.conf.local"
Ranger = { target = "~/.config/ranger", type = "symbolic" }
task = { target = "~/.config/task", type = "symbolic" }
"locale.conf" = "~/.config/locale.conf"

[win]

depends = ["default"]

[mac]

depends = ["linux"]

[archlinux]

depends = ["linux"]

[archlinux.files]

"paru.conf" = "~/.config/paru/paru.conf"
"yay.json" = "~/.config/yay/config.json"

[openSUSE]

depends = ["linux"]

[openSUSE.files]

