[helpers]

[default]
depends = []

[default.files]
"conda.yml" = "~/.condarc"
gitconfig = "~/.gitconfig"

[vim.files]
vimrc = { target = "~/.vimrc", type = "symbolic" }
gvimrc = { target = "~/.gvimrc", type = "symbolic" }


[default.variables]

