[helpers]
# hex2rgb = ".dotter/helpers/hex2rgb.rhai"

[default]

[default.variables]

username = "Xavier Younger"
locale   = "zh-cn"
os = "linux"
font = "Hack"
font_size = 12
nerd_font = "Nerd Font"
colorscheme = "dracula"
primary_color = "#CCCCCC"
background_color = "#333333"
screen_size = "1920x1080"
terminal = "xfce4-terminal"

[default.files]

gitconfig = "~/.gitconfig"
"conda.yml" = "~/.condarc"
npmrc = "~/.npmrc"
yarnrc = "~/.yarnrc"
gemrc = "~/.gemrc"
rgrc = "~/.config/rgrc"
netrc = "~/.netrc"
spacemacs = "~/.spacemacs"
Doom = { target = "~/.doom.d", type = "symbolic"}
SpaceVim = { target = "~/.SpaceVim.d", type = "symbolic"}
"cargo.toml" = "~/.cargo/config.toml"
"starship.toml" = "~/.config/starship.toml"
"fuck.py" = "~/.config/thefuck/settings.py"
"leetcode.json" = "~/.lc/plugins.json"
AppSettings = { target = "~/AppSettings", type = "symbolic" }
"s.cfg" = "~/.config/s/config"
"gpg.conf" = "~/.gnupg/gpg.conf"
"markdownlint.jsonc" = "~/.markdownlintrc"
"gh-prs.yml" = "~/.config/prs/sections.yml"

# windows diff
vim = { target = "~/.vim", type = "symbolic"}
pip = "~/.config/pip/pip.conf"
"lsd.yml" = "~/.config/lsd/config.yaml"
"bottom.toml" = "~/.config/bottom/bottom.toml"
"bat.cfg" = "~/.config/bat/config"
Alacritty = { target = "~/.config/alacritty/", type = "symbolic" }
"Alacritty/alacritty.yml" = { target = "~/.config/alacritty/alacritty.yml", type = "template" }
So = { target = "~/.config/so", type = "symbolic" }
goenv = "~/.config/go/env"
"gh.yml" = "~/.config/gh/config.yml"
vivid = { target = "~/.config/vivid", type = "symbolic" }
fd = { target = "~/.config/fd", type = "symbolic" }
"clangd.yaml" = "~/.config/clangd/config.yaml"
broot = { target = "~/.config/broot", type = "symbolic" }
helix = { target = "~/.config/helix", type = "symbolic" }
espanso = { target = "~/.config/espanso", type = "symbolic" }


[vim]

[vim.files]

vimrc = { target = "~/.vimrc", type = "symbolic" }
gvimrc = { target = "~/.gvimrc", type = "symbolic" }


[win]

depends = [ "default" ]

[win.files]

wslconfig = "~/.wslconfig"
"tabnine.toml" = "~/AppData/Roaming/TabNine/TabNine.toml"
"typora.json" = "~/AppData/Roaming/Typora/conf/conf.user.json"
"baidu_pcs.json" = "~/AppData/Roaming/BaiduPCS-Go/pcs_config.json"
"dev_sidecar.json" = "~/.dev-sidecar/config.json5"
"autohotkeyU64.ahk" = "~/.config/AutoHotkeyU64.ahk"
PowerShell = { target = "~/Documents/PowerShell", type = "symbolic" }
"PowerShell/pwsh.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"PowerShell/powershell.ps1" = "~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"
WindowsTerminal = { target = "~/AppData/Local/Microsoft/Windows Terminal", type = "symbolic" }

[shell]

depends = [ "default" ]

[shell.files]

profile = "~/.profile"
bin = { target = "~/bin", type = "symbolic" }

[bash]

[bash.files]

bash_profile = "~/.bash_profile"
inputrc = "~/.inputrc"

[zsh]

[zsh.files]

zsh = "~/zsh"
"zsh/zshenv" = "~/zsh/.zshenv"
"zsh/zprofile" = "~/zsh/.zprofile"
"zsh/zshrc" = "~/zsh/.zshrc"
"zsh/p10k" = "~/.p10k.zsh"

[fish]

[fish.files]

fish = "~/.config/fish"

[linux]

depends = [ "shell", "bash", "zsh", "fish" ]

[linux.files]

"tmux.conf.local.sh" = "~/.tmux.conf.local"
Ranger = { target = "~/.config/ranger", type = "symbolic" }
task = { target = "~/.config/task", type = "symbolic" }
"locale.conf" = "~/.config/locale.conf"

[archlinux]

depends = [ "linux" ]

[archlinux.files]

"paru.conf" = "~/.config/paru/paru.conf"
"yay.json" = "~/.config/yay/config.json"

[openSUSE]

depends = [ "linux" ]

[openSUSE.files]

