[helpers]

[default]

[default.files]
gitconfig = "~/.gitconfig"
"conda.yml" = "~/.condarc"
npmrc = "~/.npmrc"
spacemacs = "~/.spacemacs"
SpaceVim = { target = "~/.SpaceVim.d", type = "symbolic"}
"cargo.toml" = "~/.cargo/config.toml"
"starship.toml" = "~/.config/starship.toml"
"fuck.py" = "~/.config/thefuck/settings.py"
"leetcode.json" = "~/.lc/plugins.json"
AppSettings = { target = "~/AppSettings", type = "symbolic" }
Icons = { target = "~/Icons", type = "symbolic" }
Wallpaper = { target = "~/Wallpaper", type = "symbolic" }

# windows diff
pip = "~/.config/pip/pip.conf"
"lsd.yml" = "~/.config/lsd/config.yaml"
"bottom.toml" = "~/.config/bottom/bottom.toml"
"bat.cfg" = "~/.config/bat/config"
Alacritty = { target = "~/.config/alacritty/", type = "symbolic" }
So = { target = "~/.config/so", type = "symbolic" }
"s.cfg" = "~/.config/s/config"

[default.variables]
username = "Xavier Younger"
# locale   = "zh-cn"


[vim]

depends = [ "default" ]

[vim.files]
vimrc = { target = "~/.vimrc", type = "symbolic" }
gvimrc = { target = "~/.gvimrc", type = "symbolic" }


[win]
depends = [ "default" ]

[win.files]
wslconfig = "~/.wslconfig"
"tabnine.toml" = "~/AppData/Roaming/TabNine/TabNine.toml"
"typora.json" = "~/AppData/Roaming/Typora/conf/conf.user.json"
"baidu_pcs.json" = "~/AppData/Roaming/BaiduPCS-Go/pcs_config.json"
"dev_sidecar.json" = "~/.dev-sidecar/config.json5"
"autohotkeyU64.ahk" = "~/.config/AutoHotkeyU64.ahk"
PowerShell = { target = "~/Documents/PowerShell/cfg", type = "symbolic" }
"pwsh.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"powershell.ps1" = "~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"
WindowsTerminal = { target = "~/AppData/Local/Microsoft/Windows Terminal", type = "symbolic" }

