includes = [".dotter/windows.toml"]

# An array of the names of all packages that are selected.
# Only the files and variables that belong to packages in this list are kept.
packages = ["win"]

# File target locations can be overridden in local.toml
# I need to define some machine-specific files.
# Disabling files is possible by setting them to the special value "".
[files]

# I need to define some machine-specific variables.
[variables]

