# Windows OS-specific configuration

[default.variables]
os = "windows"
nerd_font = "NF"
colorscheme = "nord"

[default.files]
pip = "~/AppData/Roaming/pip/pip.ini"
"lsd.yml" = "~/AppData/Roaming/lsd/config.yaml"
"bottom.toml" = "~/AppData/Roaming/bottom/bottom.toml"
"bat.cfg" = "~/AppData/Roaming/bat/config"
Alacritty = { target = "~/AppData/Roaming/alacritty", type = "symbolic" }
"Alacritty/alacritty.yml" = { target = "~/AppData/Roaming/alacritty/alacritty.yml", type = "template" }
So = { target = "~/AppData/Roaming/Sam Tay/so/config", type = "symbolic" }
"s.cfg" = "~/AppData/Roaming/s/config"
goenv = "~/AppData/Roaming/go/env"

[vim.files]
vimrc = { target = "~/_vimrc", type = "symbolic" }
gvimrc = { target = "~/_gvimrc", type = "symbolic" }

