# Windows OS-specific configuration

[default.variables]
os = "windows"
nerd_font = "NF"
colorscheme = "nord"

[default.files]
pip = "~/AppData/Roaming/pip/pip.ini"
"lsd.yml" = "~/AppData/Roaming/lsd/config.yaml"
"bottom.toml" = "~/AppData/Roaming/bottom/bottom.toml"
"bat.cfg" = "~/AppData/Roaming/bat/config"
Alacritty = { target = "~/AppData/Roaming/alacritty", type = "symbolic" }
"Alacritty/alacritty.yml" = { target = "~/AppData/Roaming/alacritty/alacritty.yml", type = "template" }
So = { target = "~/AppData/Roaming/Sam Tay/so/config", type = "symbolic" }
goenv = "~/AppData/Roaming/go/env"
"gh.yml" = "~/AppData/Roaming/Github CLI/config.yml"
vivid = { target = "~/AppData/Roaming/vivid", type = "symbolic" }
fd = { target = "~/AppData/Roaming/fd", type = "symbolic" }
"clangd.yaml" = "~/AppData/Local/clangd/config.yaml"
broot = { target = "~/AppData/Roaming/dystroy/broot/config", type = "symbolic" }

[vim.files]
vimrc = { target = "~/_vimrc", type = "symbolic" }
gvimrc = { target = "~/_gvimrc", type = "symbolic" }

