source ~/.profile

# ~/.zshenv should only be a one-liner that sources this file
export ZDOTDIR=~/zsh

# $FPATH string variable is tied to the $fpath array variable
# fpath=(/some/extra/directory $fpath)
fpath+=~/zsh/func
